version: "3"

services:
  app:
    image: salemgolem/glazov-bot:latest
    restart: always
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHATID: ${TELEGRAM_CHATID}
      DEBUG: ${DEBUG}