---
version: "3"

services:
  app:
    build:
      target: dev
    volumes:
      - .:/opt/app/api
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHATID: ${TELEGRAM_CHATID}
      DEBUG: ${DEBUG}